@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 25 21:15:27 +0300 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tally_testbench_behav -key {Behavioral:sim_1:Functional:tally_testbench} -tclbatch tally_testbench.tcl -view C:/Users/khanh/OneDrive - O365 Turun yliopisto/Desktop/HDL homework/Ex1/Ex1/tally_testbench_behav.wcfg -log simulate.log"
call xsim  tally_testbench_behav -key {Behavioral:sim_1:Functional:tally_testbench} -tclbatch tally_testbench.tcl -view C:/Users/khanh/OneDrive - O365 Turun yliopisto/Desktop/HDL homework/Ex1/Ex1/tally_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
