# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VHDL/Ex5/Ha_Do_2407698-E5-Vivado/Ha_Do_2407698-E5-Vivado.srcs/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/design_1_pulse_detector_0_0.xci
# IP: The module: 'design_1_pulse_detector_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VHDL/Ex5/Ha_Do_2407698-E5-Vivado/Ha_Do_2407698-E5-Vivado.gen/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/constraints/pulse_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pulse_detector_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/VHDL/Ex5/Ha_Do_2407698-E5-Vivado/Ha_Do_2407698-E5-Vivado.srcs/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/design_1_pulse_detector_0_0.xci
# IP: The module: 'design_1_pulse_detector_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VHDL/Ex5/Ha_Do_2407698-E5-Vivado/Ha_Do_2407698-E5-Vivado.gen/sources_1/bd/design_1/ip/design_1_pulse_detector_0_0/constraints/pulse_detector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pulse_detector_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
